name: kronk
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+15


environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.0
  hive_ce_flutter: ^2.3.1
  google_sign_in: ^7.1.1
  dio: ^5.8.0+1
  web_socket_channel: ^3.0.3
  rive: ^0.13.20
  equatable: ^2.0.7
  google_fonts: ^6.2.1
  flutter_riverpod: ^2.6.1
  flutter_bloc: ^9.1.1
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.6
  connectivity_plus: ^6.1.4
  cached_network_image: ^3.4.1
  flutter_image_compress: ^2.4.0
  permission_handler: ^12.0.1
  image_picker: ^1.1.2
  crop_your_image: ^2.0.0
  image: ^4.5.4
  url_launcher: ^6.3.2
  jwt_decoder: ^2.0.1
  tuple: ^2.0.2
  logger: ^2.6.1
  shimmer: ^3.0.0
  visibility_detector: ^0.4.0+2
  video_player: ^2.10.0
  uuid: ^4.5.1
  mime: ^2.0.0
  fl_chart: ^1.0.0
  vector_graphics: ^1.1.19
  animated_flip_counter: ^0.3.4
  go_router: ^16.0.0
  defer_pointer: ^0.0.2
  http_parser: ^4.1.2
  icons_plus: ^5.0.0
  loading_animation_widget: ^1.3.0
  intl: ^0.20.2
  path_provider: ^2.1.5
  sign_in_with_apple: ^7.0.1
  firebase_crashlytics: ^5.0.0
  firebase_analytics: ^12.0.0
  crypto: ^3.0.6
  toastification: ^3.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  analyzer: ^7.6.0
  analyzer_plugin: ^0.13.4
  custom_lint: ^0.7.0
  vector_graphics_compiler: ^1.1.17
  riverpod_lint: ^2.6.5


flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/
    - assets/images/
    - assets/icons/app/
    - assets/animations/

    - path: assets/svg/
      transformers:
        - package: vector_graphics_compiler

  fonts:
    - family: KronkIcon
      fonts:
        - asset: assets/fonts/KronkIcon.ttf


flutter_launcher_icons:
  android: true
  ios: true
  image_path_android: "assets/icons/app/kronk-app-icon.png"
  image_path_ios: "assets/icons/app/kronk-app-icon.png"
  adaptive_icon_foreground: "assets/icons/app/kronk-foreground.png"
  adaptive_icon_background: "assets/icons/app/kronk-background.png"
  adaptive_icon_monochrome: "assets/icons/app/kronk-monochrome.png"
  # image_path_ios_dark_transparent: "" # Note: Apple recommends this icon to be transparent
  # image_path_ios_tinted_grayscale: "" # Note: This icon should be an grayscale image. Use
  desaturate_tinted_to_grayscale_ios: true
  min_sdk_android: 28
  remove_alpha_ios: true


flutter_native_splash:
  color: "#aed7f5"
  color_dark: "#0C0F15"
  color_android: "#aed7f5"
  color_dark_android: "#0C0F15"
  color_ios: "#aed7f5"
  color_dark_ios: "#0C0F15"
  image: "assets/icons/app/android12splash.png"
  image_dark: "assets/icons/app/android12splash-dark.png"
  android: true
  ios: true
  web: false

  android_12:
    color: "#aed7f5"
    color_dark: "#0C0F15"
    image: "assets/icons/app/android12splash.png"
    image_dark: "assets/icons/app/android12splash-dark.png"
