// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8KiLDINE6KiMiFnM0QldxAO7_dQQ95h8',
    appId: '1:1081239849482:android:55637528117a768b4b2df3',
    messagingSenderId: '1081239849482',
    projectId: 'kronk-production',
    storageBucket: 'kronk-production.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9qLiQj9b0gFeQJ3TYYtJ3PEf1MTUreeM',
    appId: '1:1081239849482:ios:5e493295a3a90d6b4b2df3',
    messagingSenderId: '1081239849482',
    projectId: 'kronk-production',
    storageBucket: 'kronk-production.firebasestorage.app',
    androidClientId: '1081239849482-f0jqc0orfs1h1737oi8fljd7rlbp6sd1.apps.googleusercontent.com',
    iosClientId: '1081239849482-2a38fjh12drhgrku9uat15c5l4bl0quh.apps.googleusercontent.com',
    iosBundleId: 'uz.kronk.kronk',
  );
}
